window.globalData = window.globalData || {};

Object.assign(window.globalData, {
	australia: {
		name: "Australia",
		continent: "oceania",
		status: "green",
		legal:
			"Robust Protections and Marriage Equality. Australia is a global leader in LGBTQ+ rights, having legalized same-sex marriage via a historic national postal survey and subsequent parliamentary vote in December 2017. Anti-discrimination laws are deeply entrenched at both the federal level (Sex Discrimination Act 1984) and within individual states, protecting citizens and visitors from bias in employment, education, and services. In 2024 and 2025, several states passed further legislation to ban 'conversion therapy' and streamline the process for transgender individuals to amend birth certificates without requiring surgery. The legal system recognizes a wide range of gender identities, with 'X' markers available on passports. While religious exemptions exist in some private school sectors, the general legal posture is one of high protection and proactive equality, supported by the Australian Human Rights Commission.",
		travel:
			"High Visibility and Safety. Australia is exceptionally safe for LGBTQ+ travelers. Cities like Sydney, Melbourne, and Brisbane are world-renowned for their inclusive atmospheres and massive pride celebrations, most notably the Sydney Gay and Lesbian Mardi Gras. Public Displays of Affection (PDA) are normal and generally accepted without second thought in urban and coastal areas. Travelers will find 'Safe Space' stickers in many business windows, indicating an inclusive environment. While the 'Outback' and smaller rural towns are more traditional, the Australian culture of 'mateship' typically ensures that travelers are treated with respect as long as local social norms are followed. There are no travel restrictions related to HIV status, and the tourism industry is highly attuned to the needs of diverse travelers, offering numerous queer-specific tours and luxury accommodations.",
		culture:
			"Diverse, Urban, and Celebratory. Australian culture is characterized by a 'live and let live' attitude. In urban centers, queer culture is not just tolerated but is a major part of the mainstream social fabric. The 2021 Census and subsequent 2024 surveys indicate a steady increase in the number of people identifying as part of the LGBTQ+ community, particularly among younger generations. There is a vibrant nightlife scene, with 'Oxford Street' in Sydney remaining a historic heart of the community. Indigenous Australian cultures also have a long history of recognizing 'Sistergirls' and 'Brotherboys' (transgender Aboriginal and Torres Strait Islander people), adding a rich, ancestral layer to the country's understanding of gender. While some conservative pockets remain in the outer suburbs, the overarching national culture is one of celebratory diversity and social progress.",
		health:
			"Advanced and LGBTQ-Competent Care. The Australian healthcare system (Medicare) provides high-quality, inclusive care. For travelers, private clinics in every major city specialize in sexual health and gender-affirming care. Australia has been a pioneer in PrEP accessibility, leading to some of the lowest HIV transmission rates in the world; pharmacists are highly familiar with these medications. In 2026, gender-affirming hormone therapy is widely understood by General Practitioners, and emergency rooms follow strict non-discrimination protocols. Hospitals like St Vincent's in Sydney are historically significant for their compassionate care for the community. Visitors should maintain comprehensive travel insurance to cover the high costs of private treatment, but they can expect to be treated with dignity and professional expertise regardless of where they seek help in the country.",
		posture: "Full Inclusion - Nationwide marriage equality, strong federal anti-bias laws, and world-leading inclusive healthcare.",
		sources: ["https://en.wikipedia.org/wiki/LGBT_rights_in_Australia", "https://www.equaldex.com/region/australia"],
	},
	fiji: {
		name: "Fiji",
		continent: "oceania",
		status: "yellow",
		legal:
			"Progressive Constitution, Social Friction. Fiji's 2013 Constitution was groundbreaking as it was one of the first in the world to explicitly ban discrimination based on sexual orientation and gender identity (Section 26). Same-sex sexual activity has been legal since 2010. However, the legal landscape remains contradictory in 2026; while discrimination is unconstitutional, there is no legal recognition for same-sex unions or marriage. Transgender individuals live in a legal gray area, as there is currently no administrative process to change legal gender markers on official documents. While the 'Bill of Rights' provides a strong theoretical shield, the lack of specific secondary legislation means that LGBTQ+ citizens often find it difficult to seek justice for housing or workplace discrimination in practice, as the court processes can be lengthy and expensive.",
		travel:
			"Island Hospitality with Traditional Bounds. Fiji is generally safe for travelers due to a culture that prides itself on 'Bula' hospitality. However, it is a conservative and deeply religious society. In the 2024–2026 travel seasons, the 'Yellow' advisory remains because of the gap between the law and social reality. PDA is discouraged for all couples in villages and rural areas, but same-sex couples should exercise particular discretion to avoid harassment. Most large resorts on Denarau Island or the Mamanuca Islands are 'queer-friendly' and very accustomed to international diversity. However, venturing off the resort path requires a shift toward modesty. Transgender travelers may encounter confusion or extra scrutiny at security checkpoints if their appearance does not match their passport, though this is usually handled with curiosity rather than malice. Discretion is the key to a smooth experience.",
		culture:
			"Deeply Religious and Communal. Fijian life is centered around the 'Vanua' (the land and people) and the Church. Christianity, Hinduism, and Islam play massive roles in daily life, and traditional leaders (Chiefs) still hold significant social sway. Consequently, 'non-traditional' identities are often viewed through a lens of religious taboo. Despite this, there is a small but resilient 'Pride Fiji' movement in Suva. Interestingly, Fiji has a traditional place for 'mid-gender' identities, similar to the Polynesian 'Fa'afafine,' though this is more recognized in certain communal settings than in modern law. Visitors will find that locals are rarely confrontational—hospitality is a point of national honor—but being 'out' in a local village setting is still considered culturally inappropriate and may lead to social exclusion for the hosts.",
		health:
			"Basic Facilities, High Stigma. Healthcare in Fiji is adequate for minor issues but limited for specialized needs. In Suva and Nadi, private hospitals provide the best care for travelers. While HIV treatment is available, 2025 reports indicate that social stigma remains a significant barrier to confidential care in public clinics. There are no specialized gender-affirming healthcare services in Fiji; residents typically travel to Australia or New Zealand for such needs. For LGBTQ+ travelers, it is vital to bring a full supply of all medications, including PrEP or HRT, as these can be extremely difficult to source locally and may be questioned by customs or local doctors who lack training in LGBTQ-specific health. The 'Medical Services Pacific' (MSP) clinic in Suva is the most recommended point of contact for sensitive or inclusive care.",
		posture: "Confident Discretion - Constitutional protections exist, but social conservatism and religious influence are dominant.",
		sources: ["https://en.wikipedia.org/wiki/LGBT_rights_in_Fiji", "https://www.equaldex.com/region/fiji"],
	},
	kiribati: {
		name: "Kiribati",
		continent: "oceania",
		status: "red",
		legal:
			"Colonial-Era Criminalization. In 2026, Kiribati remains one of the few countries in Oceania where same-sex acts between men are technically illegal under the Penal Code, carrying a sentence of up to 14 years, though enforcement is rare. There are no legal protections against discrimination for LGBTQ+ individuals, and gender identity is not legally recognized. The legal framework is heavily influenced by traditional 'Te Kiritimati' customs and strict Christian doctrine, making legislative reform a low priority for the government. There is currently no active movement within the legislative body to decriminalize these acts or introduce civil unions.",
		travel:
			"Extreme Caution Required. Kiribati is a highly traditional and remote nation. Travelers should practice total discretion. Any public display of same-sex affection is likely to result in significant social hostility or police intervention. The 'Red' status is assigned due to the combination of legal risk and the extreme isolation of the islands—if a traveler encounters trouble, consular assistance may be days away. Transgender travelers may face significant difficulty as there is almost no local understanding of gender diversity outside of binary norms. Visitors are guests in a society where privacy is a luxury; staying in major hotels in South Tarawa provides some shield, but even there, discretion is mandatory.",
		culture:
			"Village Centric and Christian. Life in Kiribati is governed by the 'Maneaba' (community meeting house) system. Cultural norms emphasize communal harmony and adherence to traditional Christian values. LGBTQ+ identities are largely invisible in public life and are often regarded as an external 'Western' influence that contradicts local heritage. While the people are generally peaceful and hospitable, this hospitality is predicated on visitors respecting local taboos. Discussion of LGBTQ+ issues is highly sensitive and generally avoided in public discourse. For a visitor, the culture is one of 'unspoken boundaries'—as long as your private life remains strictly private, you will be treated with the standard hospitality shown to all guests.",
		health:
			"Very Limited Resources. Healthcare is rudimentary and concentrated in South Tarawa. There is no LGBTQ-specific health infrastructure. HIV/AIDS awareness is growing but remains hampered by social stigma and the remote nature of the islands. Gender-affirming care is non-existent. Travelers must bring all necessary medications with them, as pharmacies are frequently undersupplied. In a medical emergency, evacuation to Fiji or Australia is the only reliable option. For sensitive health issues, travelers should wait until they reach a more developed hub in the region.",
		posture: "Total Discretion - Same-sex acts remain illegal; high religious and traditional influence; minimal infrastructure for assistance.",
		sources: ["https://www.humandignitytrust.org/country-profile/kiribati/", "https://en.wikipedia.org/wiki/LGBT_rights_in_Kiribati"],
	},
	marshall_islands: {
		name: "Marshall Islands",
		continent: "oceania",
		status: "yellow",
		legal:
			"Legalized but Unprotected. Same-sex sexual acts have been legal in the Marshall Islands since 2005. While this puts them ahead of some neighbors, there are no comprehensive anti-discrimination laws that protect LGBTQ+ people in housing or employment. Same-sex marriage is not recognized. In recent years (2023–2025), there has been minor discussion regarding human rights updates, but the government remains cautious due to the influence of religious groups. There is no formal legal process for changing gender markers, leaving transgender citizens in a state of legal invisibility.",
		travel:
			"Safety through Privacy. The Marshall Islands are generally safe for travelers, with low crime rates. However, like much of Micronesia, it is a conservative society. 'Yellow' status is due to the lack of social infrastructure for LGBTQ+ people. PDA is culturally inappropriate for all couples and should be strictly avoided by same-sex couples to prevent unwanted attention. Travelers in Majuro will find a more modern atmosphere, but the outer atolls are strictly traditional. Transgender travelers are unlikely to face harassment but may deal with confusion or misgendering due to a lack of local awareness. Respecting local 'Kajin Majel' (Marshallese) customs is the best way to ensure a peaceful visit.",
		culture:
			"Matrilineal and Modest. Marshallese culture is traditionally matrilineal, but modern life is heavily influenced by Protestant Christianity. This has created a culture that is modest and private. While there isn't the active hostility found in 'Red' status countries, there is a distinct lack of public queer life. Culture here is about 'keeping face'; as long as a traveler’s sexuality is not a point of public display, it will not be a point of conflict. There is an emerging youth culture that is more aware of global LGBTQ+ trends, but the elders and religious leaders still set the social tone for the islands.",
		health:
			"Adequate in Majuro. Healthcare is centered around Majuro and Ebeye. While basic services are available, specialized LGBTQ+ care—including gender-affirming therapy—is not. HIV services are available through the Ministry of Health and are generally professional, though privacy in such a small community can be a concern for locals. Travelers should bring a full supply of any specialized medications. For any serious health concerns, medical evacuation to Honolulu or Guam is common, as local facilities lack advanced diagnostic equipment.",
		posture: "Cautious Discretion - Acts are legal, but social norms are conservative and legal protections are absent.",
		sources: ["https://en.wikipedia.org/wiki/LGBT_rights_in_the_Marshall_Islands", "https://www.equaldex.com/region/marshall-islands"],
	},
	micronesia: {
		name: "Micronesia",
		continent: "oceania",
		status: "yellow",
		legal:
			"Legal but Lacking Framework. The Federated States of Micronesia (FSM) has no laws criminalizing same-sex acts, and the 2018 Civil Rights Act was updated to include protections against discrimination based on sexual orientation. However, these protections are rarely tested in court and do not explicitly include gender identity. Same-sex marriage is not recognized, and there is no legal framework for gender recognition for transgender individuals. The legal system is a mix of U.S.-style law and traditional customary law, which can lead to inconsistent protection depending on which state (Yap, Chuuk, Pohnpei, or Kosrae) you are in.",
		travel:
			"State-by-State Variance. Safety for travelers varies across the four states. Pohnpei (the capital) is the most cosmopolitan and generally safe, while Chuuk and Kosrae are significantly more conservative. 'Yellow' status reflects this inconsistency. Same-sex couples should avoid PDA entirely to respect local religious sensibilities. In Yap, traditional culture is very strong, and visitors are expected to follow 'The Yapese Way.' Transgender travelers may find the gender binary to be very strictly enforced socially. Generally, visitors are safe from violence, but social coldness or 'polite exclusion' may occur if one is overtly 'out' in a traditional setting.",
		culture:
			"Traditional and Diverse. Each state has its own distinct language and culture, but all share a strong emphasis on family and church. Respect for elders and traditional chiefs is paramount. Public life is modest; sexuality is considered a deeply private matter. While there are no 'gay bars,' there is a quiet, private tolerance for locals who are known to be 'different,' provided they do not challenge the social order. For a visitor, the culture is one of 'observational respect'—watch how locals behave and mirror their modesty. The influence of the U.S. (via the Compact of Free Association) means that younger people are increasingly aware of global LGBTQ+ movements, but this hasn't yet translated into a public 'scene.'",
		health:
			"Variable and Remote. Healthcare is basic across the FSM. Pohnpei has the most reliable facilities, but specialized LGBTQ+ health care is non-existent. HIV care is available but often stigmatized. Travelers must carry all required medications, as sourcing anything specific like HRT or PrEP is nearly impossible locally. In the event of a major medical issue, evacuation to Guam or Hawaii is the standard procedure. Local doctors may have limited exposure to LGBTQ-specific health needs, so self-reliance and pre-travel preparation are essential.",
		posture: "Modest Discretion - Legal acts and basic protections exist, but religious and traditional state laws vary widely in social practice.",
		sources: [
			"https://en.wikipedia.org/wiki/LGBT_rights_in_the_Federated_States_of_Micronesia",
			"https://www.state.gov/reports/2023-country-reports-on-human-rights-practices/federated-states-of-micronesia/",
		],
	},
	nauru: {
		name: "Nauru",
		continent: "oceania",
		status: "yellow",
		legal:
			"Recent Decriminalization. Nauru made headlines in 2016 by decriminalizing same-sex acts between men as part of a major overhaul of its Crimes Act. Despite this legal victory, there are no laws that prohibit discrimination based on sexual orientation or gender identity, and same-sex marriage remains unrecognized. The legal system is still maturing, and while the 2016 reform was a massive step forward, there has been little legislative movement since to provide a comprehensive human rights framework for the LGBTQ+ community. Gender identity remains a legal void with no pathway for legal recognition.",
		travel:
			"Isolated and Small. Nauru is one of the smallest and least-visited countries in the world. Its 'Yellow' status is largely due to its extreme isolation and the lack of established precedent for LGBTQ+ travel. It is generally safe from a crime perspective, but the social atmosphere is conservative. Discretion is advised regarding PDA. Most social life revolves around a few hotels and restaurants where international workers and locals mix. Transgender travelers may find themselves the object of curiosity due to the small, tight-knit nature of the population. There is no active hostility, but there is also no 'community' to plug into if a traveler needs support.",
		culture:
			"Tight-Knit and Traditional. Nauruan culture is defined by its small population and history of phosphate mining wealth and subsequent economic shifts. Family ties are the most important social structure. While the 2016 decriminalization shows a move toward modernization, the majority of the population remains socially conservative and Christian. There is an 'everybody knows everybody' dynamic, which means privacy is hard to maintain. For a visitor, this means being 'out' will likely become common knowledge very quickly. The social response is usually one of quiet observation rather than confrontation, provided the visitor remains respectful of local modesty norms.",
		health:
			"Limited and Specialized. Healthcare on Nauru is basic. The Republic of Nauru Hospital handles most needs, but for anything specialized, patients are often sent to Australia. There are no LGBTQ-specific health services. HIV services are technically available, but the small size of the island makes confidential testing difficult for locals. Travelers should bring every medication they might need. Because of the island's unique history as a regional processing center for refugees, there is a presence of international medical staff who may be more familiar with diverse health needs than the local generalists, but this is not guaranteed.",
		posture: "Quiet Discretion - Same-sex acts are legal, but the society is small, traditional, and lacks protective infrastructure.",
		sources: ["https://en.wikipedia.org/wiki/LGBT_rights_in_Nauru", "https://www.equaldex.com/region/nauru"],
	},
	new_zealand: {
		name: "New Zealand",
		continent: "oceania",
		status: "green",
		legal:
			"A Global Leader in Equality. New Zealand’s legal framework is among the most protective in the world for LGBTQ+ individuals. Same-sex sexual activity has been legal since 1986, and the landmark Marriage (Definition of Marriage) Amendment Act 2013 legalized same-sex marriage. Anti-discrimination protections are robust; the Human Rights Act 1993 explicitly prohibits discrimination based on sexual orientation and gender identity in employment, housing, and public services. In 2022, the 'Conversion Practices Prohibition Legislation Act' was passed, criminalizing practices that attempt to change a person's sexual orientation or gender identity. Furthermore, 'self-identification' laws passed in 2023 allow transgender and non-binary people to update their birth certificates via a simple administrative process, removing the previous requirement for medical intervention or court hearings.",
		travel:
			"Welcoming and High-Visibility. Travelers will find New Zealand to be exceptionally safe and inclusive. High-visibility support is common, with many businesses displaying Pride stickers and rainbow flags, particularly in urban centers. Public Displays of Affection (PDA) are widely accepted for all couples and rarely attract negative attention. The 'Rainbow Tick' certification program helps travelers identify LGBTQ-inclusive businesses and workplaces. While rural areas are generally safe, they tend to be more traditional, though hospitality (Manaakitanga) remains a core cultural value that extends to all visitors. Major events like 'Winter Pride' in Queenstown and the 'Auckland Pride Festival' are highlights of the social calendar, drawing thousands of international visitors annually. There are no specific safety restrictions for LGBTQ+ travelers entering or moving through the country.",
		culture:
			"Māori Values and Modern Inclusion. New Zealand culture is a blend of indigenous Māori traditions and modern Western values. The Māori concept of 'Takatāpui'—which encompasses both Māori identity and diverse sexualities or gender identities—is a respected and vital part of the national heritage. This cultural intersection provides a unique level of social acceptance compared to other Western nations. Surveys from 2024–2025 show that over 80% of New Zealanders support LGBTQ+ rights, reflecting a society that values 'fairness for all.' While a small conservative minority exists, the social 'norm' is one of active inclusion rather than mere tolerance. The capital, Wellington, is often cited as one of the most LGBTQ-friendly cities globally, boasting a vibrant queer nightlife and a political atmosphere that consistently champions diversity in the Beehive (Parliament).",
		health:
			"World-Class and Inclusive Care. The healthcare system is highly advanced and LGBTQ-competent. In 2026, gender-affirming healthcare is accessible through the public health system (Te Whatu Ora), though wait times for specific surgeries can vary. HIV care is state-of-the-art; U=U (Undetectable = Untransmittable) is a central pillar of public health campaigns, and PrEP is widely available and subsidized for residents. For travelers, private clinics like 'Sexual Wellbeing Aotearoa' offer professional, non-judgmental services. Pharmacies in both rural and urban areas are well-stocked and familiar with hormone replacement therapy (HRT) medications. Emergency services are reliable and treat all patients with dignity. Visitors should ensure they have travel insurance, as while the care is excellent, costs for non-residents can be high in the private sector.",
		posture: "Full Inclusion - Comprehensive legal protection, high social acceptance, and specialized healthcare availability.",
		sources: ["https://en.wikipedia.org/wiki/LGBT_rights_in_New_Zealand", "https://www.hrc.co.nz/our-work/lgbti-rights/"],
	},
	palau: {
		name: "Palau",
		continent: "oceania",
		status: "yellow",
		legal:
			"Legalized with Recent Progress. Same-sex acts have been legal in Palau since 2014, when the nation adopted a new Penal Code. Despite this, the constitution was amended in 2008 to define marriage as between a man and a woman, effectively banning same-sex marriage. There are currently no laws that protect LGBTQ+ individuals from discrimination in the private sector, though government employees have some basic protections. In 2024, there were minor legislative discussions regarding hate crime protections, but no significant bills have passed as of 2026. Transgender individuals do not have a legal mechanism to change their gender on official documents.",
		travel:
			"Safety in Discretion. Palau is a premier diving destination and is very accustomed to international tourists. It is generally safe for LGBTQ+ travelers, but it remains a conservative society. 'Yellow' status is due to the constitutional marriage ban and social traditionalism. PDA is generally frowned upon for all couples in public, and same-sex couples should be particularly mindful. Most luxury resorts are welcoming and inclusive. Transgender travelers are unlikely to face hostility, but they should be prepared for some curiosity or administrative confusion at the airport. The Palauan people are known for being friendly and polite, and as long as visitors respect local modesty norms, they will likely have a trouble-free stay.",
		culture:
			"Matrilineal and Respectful. Palau has a traditional matrilineal social structure, which gives women a high degree of respect and power in the community. While this doesn't directly translate to LGBTQ+ rights, it does create a social fabric that values harmony and 'Omengull' (respect). Most Palauans are Christian, and the church has a strong influence on social views regarding 'non-traditional' lifestyles. However, there is a growing 'live and let live' attitude among the younger generation in Koror. There is no visible 'gay scene,' but there is a quiet tolerance. Visitors should avoid being overtly political about LGBTQ+ issues, as Palauan culture values subtle communication over direct confrontation.",
		health:
			"Adequate for Travelers. Healthcare in Palau is among the best in the Micronesian region, centered at the Belau National Hospital in Koror. While basic services are good, specialized LGBTQ+ health care is not available. HIV care is available and confidential, but stigma remains a concern for locals. Travelers should bring all their own specialized medications, including HRT. In the event of a severe medical emergency, evacuation to the Philippines, Guam, or Taiwan is common. For general health needs, the medical staff is professional and generally treats visitors with the high degree of respect that is standard in Palauan culture.",
		posture: "Polite Discretion - Acts are legal, but marriage is constitutionally restricted and social norms remain traditional.",
		sources: ["https://en.wikipedia.org/wiki/LGBT_rights_in_Palau", "https://www.equaldex.com/region/palau"],
	},
	papua_new_guinea: {
		name: "Papua New Guinea",
		continent: "oceania",
		status: "red",
		legal:
			"Colonial Legacies and Criminalization. As of 2026, Papua New Guinea (PNG) maintains colonial-era laws that criminalize male-to-male sexual activity. Under Section 210 of the Penal Code, 'unnatural offences' (specifically anal intercourse) carry a penalty of up to 14 years in prison, while Section 212 penalizes 'indecent practices between males' with up to 3 years. While these laws are sporadically enforced, arrests occurred as recently as 2022. The Constitution does not recognize sexual orientation or gender identity as protected grounds, and Prime Minister James Marape reaffirmed in 2023 that the government has no intention of legitimizing LGBTQ+ rights, citing Melanesian and Christian worldviews. There are no legal pathways for gender recognition, and same-sex marriage is strictly prohibited, with the state maintaining a rigid binary view of gender and family.",
		travel:
			"High Risk and Necessary Discretion. Travel to PNG requires extreme caution for LGBTQ+ individuals. The 'Red' status is a result of both legal criminalization and high rates of general violent crime. Public Displays of Affection (PDA) are dangerous and could lead to harassment, assault, or police intervention. Urban areas like Port Moresby and Lae have seen targeted violence against those perceived as queer, particularly by groups from more conservative highland regions. Travelers are advised to use reputable, secure transport and avoid walking after dark. While some high-end resorts and the Hanuabada 'gay village' in Port Moresby offer a degree of sanctuary, they are exceptions in a landscape of widespread homophobia. Consular assistance is limited outside major hubs, and transgender travelers face significant risks of discrimination and harassment at all levels of transit.",
		culture:
			"Traditional Values vs. Urban Subcultures. PNG culture is a complex mosaic of over 800 indigenous groups, largely unified by a shared, modern adherence to conservative Christian doctrines. Social life is centered on the 'Wantok' system (communal kinship), which often prioritizes traditional family structures over individual identity. LGBTQ+ life is mostly invisible, though small, discreet subcultures exist in the capital. The concept of 'Melanesian Values' is frequently invoked by leaders to exclude queer identities as 'foreign' or 'unnatural.' However, some coastal communities have historically been more tolerant than the New Guinea Highlands, where gender roles are strictly policed. Public discourse on LGBTQ+ rights is often met with hostility from church leaders, who wield immense political power and frame queer advocacy as a threat to the nation's spiritual and cultural integrity.",
		health:
			"Inconsistent and Stigmatized Care. The healthcare system in PNG is fragile and often lacks basic supplies. For LGBTQ+ individuals, seeking care is fraught with the risk of 'outing' and subsequent discrimination by staff. While HIV/AIDS programs exist (funded largely by international NGOs), 2024-2025 reports indicate that stigma prevents many from accessing treatment. Gender-affirming care is non-existent, and HRT is not available through public channels. Travelers should bring a comprehensive medical kit and a full supply of all personal medications, as local pharmacies are unreliable. In the event of a medical emergency, private hospitals in Port Moresby are the only viable option, and medical evacuation to Australia is frequently required for serious conditions. Sourcing PrEP locally is extremely difficult and may be met with invasive questioning by healthcare providers.",
		posture: "Extreme Caution - Active criminalization for males, widespread social homophobia, and limited medical/legal support.",
		sources: ["https://database.ilga.org/papua-new-guinea-lgbti", "https://www.humandignitytrust.org/country-profile/papua-new-guinea/"],
	},
	samoa: {
		name: "Samoa",
		continent: "oceania",
		status: "yellow",
		legal:
			"Contradictory Laws and Third-Gender Recognition. Samoa presents a unique legal landscape in 2026. While the Crimes Act 2013 repealed laws against 'female impersonation,' it still criminalizes 'sodomy' between men (Section 67) with up to 5 years in prison. These laws are rarely enforced but remain on the books as a symbolic deterrent. Same-sex marriage was constitutionally banned in 2023, defining marriage strictly as between a man and a woman. However, the 2016 Sentencing Act includes hostility toward a group based on sexual orientation or gender identity as an aggravating factor in crimes, providing a rare layer of protection. There is no legal process to change gender markers, but the cultural recognition of the 'Fa'afafine' (third gender) ensures that gender-diverse individuals are not entirely excluded from the legal and social conversation, even if their specific rights remain uncodified.",
		travel:
			"Cultural Respect and Resort Safety. Samoa is generally safe for travelers, provided they understand the distinction between 'Fa'afafine' culture and Western 'Gay' culture. 'Yellow' status is due to the lack of legal recognition and the strong influence of the church. PDA is considered disrespectful for all couples in local villages (fales) and should be avoided. Major resorts are highly inclusive and welcoming of diverse couples. Transgender women (Fa'afafine) are a visible part of the hospitality industry, but transgender men (Fa'afatama) and gay men may find less public understanding. Security at Faleolo International Airport is professional, and while 'Rocketman' was famously banned in 2019 for violating 'Christian beliefs,' travelers themselves are unlikely to face censorship as long as they remain respectful of the 'Fa'a Samoa' (The Samoan Way) in public spaces.",
		culture:
			"The Fa'afafine and the Church. Samoan culture is a blend of deep-rooted indigenous traditions and fervent Christianity. The 'Fa'afafine' (assigned male at birth, raised with feminine roles) are a recognized and respected part of the traditional family unit, often serving as caregivers and cultural leaders. This 'third gender' status is not synonymous with Western 'gay' identity; many Samoans who accept Fa'afafine may still hold conservative views on same-sex relationships. The 'Samoa Fa'afafine Association' is a powerful advocacy group that works closely with the government on human rights. Despite this, the village-based social structure remains conservative, and any challenge to the traditional 'matai' (chiefly) or church authority regarding LGBTQ+ rights is met with significant resistance. Total social acceptance is high for gender diversity, but lower for same-sex romantic visibility.",
		health:
			"Basic Care with Specialized Gaps. Healthcare in Samoa is adequate for primary needs, but with only about 120 doctors nationwide in 2025, specialized services are scarce. There is no specific gender-affirming healthcare infrastructure, though it is not explicitly banned. The Mental Health Act 2007 is progressive, stating that individuals cannot be considered mentally ill for failing to express a particular sexual orientation and banning conversion therapy by health professionals. HIV care is available but suffers from the small-community 'fishbowl' effect where privacy can be a concern. Travelers must bring their own supplies of PrEP, HRT, or other specialized medications. For serious emergencies, patients are typically stabilized and then evacuated to Auckland or Pago Pago. Most medical staff are accustomed to treating Fa'afafine patients with dignity and respect.",
		posture: "Respectful Discretion - Indigenous third-gender acceptance exists alongside conservative Christian laws and a ban on same-sex marriage.",
		sources: ["https://en.wikipedia.org/wiki/LGBTQ_rights_in_Samoa", "https://www.equaldex.com/region/samoa"],
	},
	solomon_islands: {
		name: "Solomon Islands",
		continent: "oceania",
		status: "red",
		legal:
			"Total Criminalization and Obsolete Enforcement. In 2026, the Solomon Islands criminalizes same-sex sexual activity for both men and women under the Penal Code 1996. Sections 160-162 prohibit 'buggery' and 'gross indecency' with penalties of up to 14 years in prison. While there hasn't been a reported arrest since a 2003 case involving a lesbian woman, the government reiterated to the UN in recent cycles that it has no intention of decriminalizing these acts. There are no anti-discrimination protections in employment or housing, and the 2014 draft of the new Constitution removed proposed protections for sexual orientation. There is no legal recognition for same-sex couples or any process for gender transition, making the Solomon Islands one of the most legally restrictive environments in the Pacific for LGBTQ+ individuals.",
		travel:
			"Privacy is Mandatory. The Solomon Islands is a 'Red' status destination because the mere act of being LGBTQ+ is a felony. While the people are generally hospitable, travelers must exercise absolute discretion. PDA is a crime ('gross indecency') and could lead to arrest or social backlash. In the capital, Honiara, and on major dive liveaboards, travelers have more leeway, but in rural villages, traditional and religious taboos are strictly enforced. Transgender travelers are at a high risk of harassment as there is almost no local vocabulary for gender transition outside of binary norms. It is recommended that visitors keep their personal lives entirely private and avoid 'out' digital footprints while in the country. Safety depends heavily on remaining an 'unassuming tourist' and adhering to local modest dress codes.",
		culture:
			"Christian Conservatism and Customary Law. The Solomon Islands is a deeply religious society where 90% of the population identifies as Christian. The Church, alongside traditional 'Kastom' (customary law), dictates social behavior. LGBTQ+ issues are rarely discussed in public, and when they are, the discourse is usually framed by political and religious leaders as a 'sinful' Western import. There is no visible LGBTQ+ community or 'scene.' Unlike some of its Polynesian neighbors, there is no widely recognized 'third gender' role in Melanesian Solomon Islander culture. Privacy is the social currency here; what happens behind closed doors is often ignored, but public challenges to gender or sexual norms are seen as an affront to the community and the church. Success for a traveler involves blending in and respecting these unspoken boundaries.",
		health:
			"Minimal and Vulnerable Infrastructure. Healthcare is extremely limited and concentrated in Honiara. The National Referral Hospital is the only major facility, and it lacks specialized services for the LGBTQ+ community. HIV stigma is significant, and while some testing is available, confidentiality is a major hurdle in such a small social environment. There is no access to gender-affirming care or specialized hormones. Travelers must bring all medications with them and carry a doctor's note for any HRT to avoid issues at customs. In the event of a medical emergency, evacuation to Brisbane is the standard protocol. For sensitive health issues, visitors should seek help through private channels or wait until they reach a more developed medical hub. Local medical staff are generally not trained in SOGIESC (Sexual Orientation, Gender Identity and Expression, and Sex Characteristics) issues.",
		posture: "Extreme Caution - Criminalization of both male and female acts; high religious influence and no legal protections.",
		sources: ["https://www.humandignitytrust.org/country-profile/solomon-islands/", "https://en.wikipedia.org/wiki/LGBTQ_rights_in_the_Solomon_Islands"],
	},
	tonga: {
		name: "Tonga",
		continent: "oceania",
		status: "yellow",
		legal:
			"Criminalization vs. Cultural Tolerance. Tonga’s legal system in 2026 is a relic of British protectorate laws. Section 136 of the Criminal Offences Act criminalizes 'sodomy' with a penalty of up to 10 years and potential whipping, though these are not enforced for consensual acts. In 2015, the government moved to explicitly ban same-sex marriage to prevent any future 'creep' from international human rights treaties. However, the 'Leiti' (Tonga's third gender) population is recognized and permitted to operate advocacy groups like the Tonga Leitis Association (TLA). There is no legal recognition of gender identity and cross-dressing is technically illegal under vague 'immoral purpose' clauses, yet in practice, Leitis are an integrated part of the social fabric. The legal posture is one of 'official disapproval' countered by 'cultural accommodation.'",
		travel:
			"Resort Comfort and Village Modesty. Tonga is safe for travelers who adhere to the kingdom's strict social codes. Sunday is a sacred day of rest where almost all activity stops; being 'loud' or 'visible' on the Sabbath is seen as provocative. Same-sex couples should avoid PDA in public, particularly near churches or in rural villages. The 'Yellow' status reflects the disconnect between the harsh legal code and the generally peaceful social reality. Transgender women will find more acceptance than gay men due to the Leiti tradition, but even then, modesty is required. In Nuku'alofa, the social scene is quiet but respectful. Travelers should be aware that while they are unlikely to be arrested, they are in a society that values hierarchy and tradition above all else. Discretion ensures a warm welcome (the 'Friendly Islands' spirit).",
		culture:
			"The Leiti Tradition and Religious Fundamentalism. Tongan culture is defined by 'Faka'apa'apa' (mutual respect). Within this, the 'Fakaleiti' (literally 'like a lady') have traditionally held roles as domestic helpers and entertainers for the royal family and nobility. This cultural space allows for gender diversity but does not necessarily translate to support for 'Gay Rights' in a Western sense. In recent years, a rise in Christian fundamentalism has put pressure on the Leiti community, leading to high-profile tragedies like the 2021 murder of TLA President Polikalepo Kefu. Despite this, the TLA remains one of the most effective LGBTQ+ organizations in the Pacific, hosting the annual 'Miss Galaxy Pageant' which is attended by members of the nobility. The culture is a tug-of-war between ancient inclusive traditions and modern, rigid religious interpretations.",
		health:
			"Adequate with High Sensitivity. Healthcare is provided through the Ministry of Health, but resources are thin. The Vaiola Hospital in Nuku'alofa is professional but lacks LGBTQ-specific training. HIV care is available but highly stigmatized; the Tonga Leitis Association often acts as a bridge for the community to access safe testing. Gender-affirming care (hormones and surgery) is not available locally. Travelers must bring their own medications, as HRT is restricted and not stocked in local pharmacies. In a medical crisis, evacuation to New Zealand is common. Visitors can expect professional treatment for general ailments, but should not expect local providers to be knowledgeable about trans-specific health or PrEP. Privacy is key when navigating the small, interconnected Tongan medical community.",
		posture: "Cautious Discretion - Harsh laws remain unenforced; third-gender Leitis are culturally integrated but face rising religious pressure.",
		sources: ["https://www.humandignitytrust.org/country-profile/tonga/", "https://www.equaldex.com/region/tonga"],
	},
	tuvalu: {
		name: "Tuvalu",
		continent: "oceania",
		status: "red",
		legal:
			"New Constitutional Bans. Tuvalu remains a highly restrictive legal environment in 2026. The Penal Code (Sections 153-155) criminalizes male-to-male 'unnatural offences' and 'indecent practices' with up to 14 years in prison. Crucially, the 2023 constitutional amendments explicitly banned same-sex marriage, defining family as a union between a man and a woman. While employment discrimination based on sexual orientation was technically banned in 2017, there is no infrastructure to enforce this, and no protections exist for gender identity. The legal system is heavily intertwined with the 'Falekaupule' (traditional island councils), which prioritize communal Christian values over individual sexual or gender expression. There are no legal avenues for gender recognition, and the overall legal trajectory has been toward more explicit restriction rather than reform.",
		travel:
			"Extreme Isolation and Social Pressure. Tuvalu is one of the world's least visited countries, and its 'Red' status is a reflection of its tiny, conservative society where privacy is non-existent. Travelers must practice total discretion. Any public display of same-sex affection is likely to result in immediate social ostracization or police involvement. Transgender travelers (outside of the local 'Pina' tradition) may face significant harassment or confusion. The isolation of the islands means that if a traveler faces a legal or social crisis, they are effectively cut off from immediate help. Security at Funafuti International Airport is basic, but the community is tight-knit; 'being known' happens instantly. For those who visit, staying in the few available guest houses and keeping a very low profile is the only way to ensure a safe trip.",
		culture:
			"The Pina and the Church. Tuvaluan culture recognizes a traditional third-gender role known as 'Pinapinaaine' or 'Pina.' Like the Samoan Fa'afafine, Pina are assigned male at birth but take on feminine roles and are integrated into the community. However, this acceptance is strictly defined by tradition; Western concepts of 'Gay' or 'Transgender' rights are often seen as a threat to the 'Tuvalu Mo Te Atua' (Tuvalu for the Almighty) national motto. The church is the center of social life, and its teachings on morality are absolute for most residents. While Pina have a small advocacy group, their focus is on cultural preservation rather than legislative change. For a visitor, the culture is one of extreme modesty—any behavior that deviates from the church-sanctioned norm is viewed with deep suspicion, regardless of the 'Pina' exception.",
		health:
			"Very Rudimentary Services. Healthcare in Tuvalu is limited to the Princess Margaret Hospital in Funafuti. Facilities are basic, and there is a permanent shortage of specialized staff and medications. There is no LGBTQ-specific health care, and HIV testing is hampered by the extreme lack of privacy on the island. Sourcing any form of hormone therapy or PrEP is impossible locally; travelers must bring a 100% complete supply of all medical needs. In a serious health emergency, the only option is a highly expensive medical evacuation to Fiji or Australia, which can be delayed by weather or flight schedules. Medical staff are generally kind but operate within the same conservative social framework as the rest of the population, meaning sensitive issues should be handled with extreme care.",
		posture: "Extreme Caution - Male acts remain illegal; new constitutional ban on marriage; tiny, highly religious community.",
		sources: ["https://database.ilga.org/tuvalu-lgbti", "https://en.wikipedia.org/wiki/LGBTQ_rights_in_Tuvalu"],
	},
	vanuatu: {
		name: "Vanuatu",
		continent: "oceania",
		status: "yellow",
		legal:
			"Legal Acts but New Marriage Bans. Vanuatu is one of the few Pacific nations where same-sex sexual activity has never been criminalized; the age of consent was equalized in 2007. However, the legal environment shifted toward conservatism in late 2024, when the parliament passed an amendment to the Marriage Act explicitly banning same-sex marriage in all forms (religious, civil, and traditional). While the Harmful Digital Communications Act 2024 protects against online denigration based on sexual orientation, there are no comprehensive civil anti-discrimination laws. The legal system remains a mix of French/English law and 'Customary Law,' the latter of which provides no recognition for LGBTQ+ identities or gender transition. The 'Yellow' status reflects this recent legislative step backward despite the decriminalized baseline.",
		travel:
			"Bula Spirit with Boundaries. Vanuatu is generally a safe and welcoming destination for LGBTQ+ travelers. The tourism industry is a major part of the economy, and resorts in Port Vila and Santo are professional and inclusive. However, outside of these areas, Vanuatu is a socially conservative country. PDA is culturally inappropriate for all couples and could attract negative attention if performed by same-sex couples. Transgender travelers are likely to be treated with curiosity rather than hostility, but should be aware that there is no local legal framework for their identity. Since the 2024 marriage ban, the government has warned against holding 'commitment ceremonies' even at private resorts. As long as travelers remain respectful of local modesty, they are likely to experience the famous Ni-Vanuatu hospitality without issue.",
		culture:
			"Kastom and Modern Advocacy. Ni-Vanuatu culture is rooted in 'Kastom' (tradition), which varies from island to island. In some areas, traditional gender-bending roles existed, but these have been largely overshadowed by modern Christian fundamentalism. However, Vanuatu is home to the 'VPride Foundation,' one of the most active and vocal LGBTQ+ organizations in the region. VPride works to bridge the gap between traditional chiefs and the queer community, holding workshops and advocacy events. Despite the 2024 marriage ban, public sentiment in urban areas is slowly shifting toward a 'live and let live' attitude. Nevertheless, the influential Vanuatu Christian Council continues to lobby for more restrictive social policies. For a visitor, the culture is one of 'polite silence'—your identity will be respected if it is not pushed as a political statement in traditional spaces.",
		health:
			"Developing but Limited. Healthcare is centered in Port Vila (Vila Central Hospital) and Luganville. While staff are generally professional, there is a lack of training regarding LGBTQ+ specific needs. HIV care is available through the Ministry of Health, and VPride has successfully campaigned to make these services more inclusive. Gender-affirming care is legal but practically non-existent due to a lack of trained specialists and resources. Travelers must bring their own supplies of PrEP and HRT. For serious medical issues, evacuation to Australia or New Caledonia is necessary. Most doctors in Port Vila are accustomed to international visitors and treat all patients with dignity, but confidentiality can be a challenge in the smaller, more remote island clinics. Bringing a private medical supply is strongly advised.",
		posture: "Cautious Discretion - Acts are legal, but a recent constitutional ban on marriage and high social conservatism define the region.",
		sources: ["https://en.wikipedia.org/wiki/LGBTQ_rights_in_Vanuatu", "https://www.equaldex.com/region/vanuatu"],
	},
});
