// data.js
// data.js
const globalData = {
	afghanistan: {
		name: "Afghanistan",
		continent: "asia",
		status: "red",
		legal: "Illegal (Death Penalty). Strict Sharia law under Taliban rule.",
		health:
			"Extremely dangerous; healthcare often requires gender-conforming behavior.",
		posture: "Extremely Hostile - Maximum monitoring advised.",
	},
	albania: {
		name: "Albania",
		continent: "europe",
		status: "yellow",
		legal:
			"Legal. Anti-discrimination laws in place, but no marriage equality.",
		health: "Basic inclusive care in Tirana; high social stigma elsewhere.",
		posture: "Slowly improving; Council of Europe monitoring.",
	},
	algeria: {
		name: "Algeria",
		continent: "africa",
		status: "red",
		legal: "Illegal. Imprisonment and fines under Penal Code.",
		health: "Stigmatized; risk of being reported by state medical staff.",
		posture: "Hostile.",
	},
	andorra: {
		name: "Andorra",
		continent: "europe",
		status: "green",
		legal: "Same-sex marriage legal since 2023.",
		health: "Universal access; high level of privacy.",
		posture: "Very stable and friendly.",
	},
	anguilla: {
		name: "Anguilla",
		continent: "americas",
		status: "green",
		legal: "Legal since 2001. No same-sex marriage yet.",
		health: "Basic medical; generally inclusive for tourists.",
		posture: "Stable - UK Overseas Territory status.",
	},
	angola: {
		name: "Angola",
		continent: "africa",
		status: "yellow",
		legal: "Decriminalized in 2021; discrimination is prohibited.",
		health: "Emerging support groups in Luanda.",
	},
	"antigua-and-barbuda": {
		name: "Antigua and Barbuda",
		continent: "americas",
		status: "green",
		legal: "Decriminalized in 2022; generally safe for tourists.",
		health: "Standard medical facilities available.",
	},
	argentina: {
		name: "Argentina",
		continent: "americas",
		status: "green",
		legal:
			"Leader in South American LGBTQ+ rights; marriage equality since 2010.",
		health: "World-class gender-affirming care and inclusive clinics.",
	},
	armenia: {
		name: "Armenia",
		continent: "europe",
		status: "yellow",
		legal: "Legal, but high levels of societal discrimination.",
		health: "Limited specialized support.",
	},
	aruba: {
		name: "Aruba",
		continent: "americas",
		status: "green",
		legal:
			"Same-sex marriage legalized in July 2024 following a high court ruling.",
		health: "Generally inclusive; mirrors Dutch standards.",
		posture: "Safe - Major tourism improvement.",
	},
	australia: {
		name: "Australia",
		continent: "oceania",
		status: "green",
		legal: "Marriage equality and strong anti-discrimination protections.",
		health: "Extensive LGBTQ+ health networks and PrEP access.",
	},
	austria: {
		name: "Austria",
		continent: "europe",
		status: "green",
		legal: "Legal marriage and strong constitutional protections.",
		health: "Highly inclusive healthcare system.",
	},
	azerbaijan: {
		name: "Azerbaijan",
		continent: "asia",
		status: "yellow",
		legal: "Legal, but frequent reports of police harassment.",
		health: "Very few safe spaces for health support.",
	},
	bahamas: {
		name: "Bahamas",
		continent: "americas",
		status: "green",
		legal: "Legal, though social conservatism remains high.",
		health: "Private clinics are generally inclusive.",
	},
	bahrain: {
		name: "Bahrain",
		continent: "asia",
		status: "red",
		legal: "Vague 'morality' laws often used against the community.",
		health: "No specific LGBTQ+ services.",
	},
	bangladesh: {
		name: "Bangladesh",
		continent: "asia",
		status: "red",
		legal: "Illegal under colonial-era laws; high social risk.",
		health: "Underground community health networks only.",
	},
	barbados: {
		name: "Barbados",
		continent: "americas",
		status: "green",
		legal: "Decriminalized in 2022; tourism is welcoming.",
		health: "Improving access to inclusive care.",
	},
	belarus: {
		name: "Belarus",
		continent: "europe",
		status: "red",
		legal: "Legal, but state-led 'propaganda' bans make it unsafe.",
		health: "Significant stigma in medical settings.",
	},
	belgium: {
		name: "Belgium",
		continent: "europe",
		status: "green",
		legal:
			"Top-tier rights; second country in the world to legalize gay marriage.",
		health: "Comprehensive and specialized LGBTQ+ centers.",
	},
	belize: {
		name: "Belize",
		continent: "americas",
		status: "yellow",
		legal: "Decriminalized in 2016; social attitudes are mixed.",
		health: "Limited specialized care.",
	},
	benin: {
		name: "Benin",
		continent: "africa",
		status: "yellow",
		legal: "Never criminalized, but lack of protective laws.",
		health: "Minimal specialized resources.",
	},
	bermuda: {
		name: "Bermuda",
		continent: "americas",
		status: "yellow",
		legal:
			"Legal but complex. Marriage protected by Privy Council; discrimination prohibited.",
		health:
			"High-quality but expensive; discreet care at Hamilton Health Centre.",
		posture:
			"Cautious - 2026 monitoring shows stable 'don't ask, don't tell' atmosphere.",
	},
	bhutan: {
		name: "Bhutan",
		continent: "asia",
		status: "yellow",
		legal: "Decriminalized in 2021; society is generally tolerant.",
		health: "Developing healthcare support.",
	},
	bolivia: {
		name: "Bolivia",
		continent: "americas",
		status: "yellow",
		legal: "Constitutional protection against discrimination exists.",
		health: "Public health system can be inconsistent.",
	},
	"bosnia-and-herzegovina": {
		name: "Bosnia and Herzegovina",
		continent: "europe",
		status: "yellow",
		legal: "Legal, but Pride events require heavy security.",
		health: "Support mostly found in Sarajevo.",
	},
	botswana: {
		name: "Botswana",
		continent: "africa",
		status: "green",
		legal: "Decriminalized in 2019; a leader in African LGBTQ+ rights.",
		health: "Increasingly inclusive public health.",
	},
	brazil: {
		name: "Brazil",
		continent: "americas",
		status: "green",
		legal: "Marriage equality and criminalized homophobia.",
		health: "Large network of specialized clinics in major cities.",
	},
	brunei: {
		name: "Brunei",
		continent: "asia",
		status: "red",
		legal: "Strict Sharia law; severe penalties including death.",
		health: "No LGBTQ+ services; high risk.",
	},
	bulgaria: {
		name: "Bulgaria",
		continent: "europe",
		status: "green",
		legal: "Legal, though constitutional ban on same-sex marriage.",
		health: "Reliable healthcare in Sofia.",
	},
	"burkina-faso": {
		name: "Burkina Faso",
		continent: "africa",
		status: "red",
		legal: "Criminalized in 2025. Prison terms for same-sex acts and marriage.",
		health: "Significant risk of discrimination in state medical facilities.",
		posture: "Hostile - Rapidly deteriorating legal climate.",
	},
	burundi: {
		name: "Burundi",
		continent: "africa",
		status: "red",
		legal:
			"Criminalized since 2009 (up to 2 years). President Ndayishimiye's 2024-2026 rhetoric has been violently homophobic.",
		health:
			"CRITICAL: MUCO Burundi (HIV NGO) was targeted in raids. Seeking care for 'homosexuality' can lead to 'incitement to debauchery' charges. Underground networks only.",
		posture:
			"Hostile - President recently revived calls for stoning; safety is currently at an all-time low (Feb 2026).",
	},
	"cabo-verde": {
		name: "Cabo Verde",
		continent: "africa",
		status: "green",
		legal: "Very progressive; anti-discrimination laws in place.",
		health: "Inclusive clinics available.",
	},
	cambodia: {
		name: "Cambodia",
		continent: "asia",
		status: "yellow",
		legal: "No laws against it; growing social acceptance in cities.",
		health: "Good support in Phnom Penh.",
	},
	cameroon: {
		name: "Cameroon",
		continent: "africa",
		status: "red",
		legal: "Active prosecution and imprisonment.",
		health: "High risk of discrimination in clinics.",
	},
	canada: {
		name: "Canada",
		continent: "americas",
		status: "green",
		legal: "Global leader in rights and protections.",
		health: "Highly specialized, universal inclusive care.",
	},
	"central-african-republic": {
		name: "Central African Republic",
		continent: "africa",
		status: "red",
		legal: "Legal but extremely unsafe due to conflict.",
		health: "Non-existent specialized care.",
	},
	chad: {
		name: "Chad",
		continent: "africa",
		status: "red",
		legal: "Criminalized since 2017.",
		health: "No resources.",
	},
	chile: {
		name: "Chile",
		continent: "americas",
		status: "green",
		legal: "Marriage equality and strong gender identity laws.",
		health: "Excellent inclusive healthcare.",
	},
	china: {
		name: "China",
		continent: "asia",
		status: "red",
		legal: "Legal, but increasing censorship and 'conversion' clinics.",
		health: "Specialized care is being restricted.",
	},
	colombia: {
		name: "Colombia",
		continent: "americas",
		status: "yellow",
		legal: "Strong legal rights, but safety varies by region.",
		health: "Great inclusive care in Bogotá and Medellín.",
	},
	comoros: {
		name: "Comoros",
		continent: "africa",
		status: "red",
		legal: "Illegal; religious influence is high.",
		health: "No resources.",
	},
	congo: {
		name: "Congo",
		continent: "africa",
		status: "yellow",
		legal: "Legal, but no protective laws.",
		health: "Minimal support.",
	},
	"cook-islands": {
		name: "Cook Islands",
		continent: "oceania",
		status: "green",
		legal: "Decriminalized in 2023.",
		health: "Small but welcoming community.",
	},
	"costa-rica": {
		name: "Costa Rica",
		continent: "americas",
		status: "green",
		legal: "Marriage equality; very safe for travel.",
		health: "Robust and inclusive medical system.",
	},
	croatia: {
		name: "Croatia",
		continent: "europe",
		status: "green",
		legal: "Life partnership is legal; safe for tourists.",
		health: "Generally inclusive in cities.",
	},
	cuba: {
		name: "Cuba",
		continent: "americas",
		status: "yellow",
		legal: "Passed a progressive family code in 2022.",
		health: "State-run LGBTQ+ health programs.",
	},
	curacao: {
		name: "Curaçao",
		continent: "americas",
		status: "green",
		legal:
			"Same-sex marriage legalized in July 2024 by the Dutch Supreme Court.",
		health: "Inclusive care available in urban centers.",
		posture: "Safe and stable.",
	},
	cyprus: {
		name: "Cyprus",
		continent: "europe",
		status: "green",
		legal: "Civil unions are legal; safe for travel.",
		health: "Good standard of inclusive care.",
	},
	czechia: {
		name: "Czechia",
		continent: "europe",
		status: "green",
		legal:
			"Civil unions expanded Jan 2025; surgery requirement for gender change ended.",
		health: "Access to gender-affirming care simplified.",
		posture: "Progressive - Moving toward full marriage equality.",
	},
	denmark: {
		name: "Denmark",
		continent: "europe",
		status: "green",
		legal: "First country to recognize same-sex partnerships (1989).",
		health: "Global standard for inclusive care.",
	},
	djibouti: {
		name: "Djibouti",
		continent: "africa",
		status: "red",
		legal: "Legal, but culturally strictly forbidden.",
		health: "No resources.",
	},
	dominica: {
		name: "Dominica",
		continent: "americas",
		status: "yellow",
		legal: "Decriminalized in 2024.",
		health: "Limited support.",
	},
	"dominican-republic": {
		name: "Dominican Republic",
		continent: "americas",
		status: "yellow",
		legal: "Legal, but high machismo and social stigma.",
		health: "Safe in tourist zones.",
	},
	ecuador: {
		name: "Ecuador",
		continent: "americas",
		status: "yellow",
		legal: "Marriage equality since 2019.",
		health: "Inclusive clinics in Quito.",
	},
	egypt: {
		name: "Egypt",
		continent: "africa",
		status: "red",
		legal: "Severe 'debauchery' crackdowns; very high risk.",
		health: "Entrapment risk in medical settings.",
	},
	"el-salvador": {
		name: "El Salvador",
		continent: "americas",
		status: "yellow",
		legal: "Legal, but high violence rates against trans people.",
		health: "NGO-led support only.",
	},
	"equatorial-guinea": {
		name: "Equatorial Guinea",
		continent: "africa",
		status: "red",
		legal: "Legal, but high harassment and stigma.",
		health: "No resources.",
	},
	eritrea: {
		name: "Eritrea",
		continent: "africa",
		status: "red",
		legal: "Strictly illegal; imprisonment.",
		health: "No resources.",
	},
	estonia: {
		name: "Estonia",
		continent: "europe",
		status: "green",
		legal: "First Baltic country to legalize marriage equality (2024).",
		health: "Highly inclusive healthcare.",
	},
	eswatini: {
		name: "Eswatini",
		continent: "africa",
		status: "red",
		legal: "Illegal; very conservative.",
		health: "Minimal resources.",
	},
	ethiopia: {
		name: "Ethiopia",
		continent: "africa",
		status: "red",
		legal: "Strictly illegal; severe social stigma.",
		health: "No resources.",
	},
	fiji: {
		name: "Fiji",
		continent: "oceania",
		status: "yellow",
		legal: "Constitution bans discrimination, but social stigma exists.",
		health: "Reliable care in Suva.",
	},
	finland: {
		name: "Finland",
		continent: "europe",
		status: "green",
		legal: "Full equality and protection.",
		health: "Excellent inclusive care.",
	},
	france: {
		name: "France",
		continent: "europe",
		status: "green",
		legal: "Marriage equality and anti-discrimination since 1985.",
		health: "Extensive inclusive health network.",
	},
	gabon: {
		name: "Gabon",
		continent: "africa",
		status: "yellow",
		legal: "Decriminalized in 2020.",
		health: "Developing support.",
	},
	gambia: {
		name: "Gambia",
		continent: "africa",
		status: "red",
		legal: "Strictly illegal; high risk.",
		health: "No resources.",
	},
	georgia: {
		name: "Georgia",
		continent: "asia",
		status: "yellow",
		legal: "Legal, but Pride events often attacked.",
		health: "NGO support in Tbilisi.",
	},
	germany: {
		name: "Germany",
		continent: "europe",
		status: "green",
		legal: "Marriage equality and ban on 'conversion' therapy.",
		health: "Highly specialized clinics nationwide.",
	},
	ghana: {
		name: "Ghana",
		continent: "africa",
		status: "red",
		legal:
			"Anti-LGBTQ Bill passed. Advocacy and care are criminalized as of 2026.",
		health: "Extremely restricted.",
		posture: "Extremely Hostile - Severe surveillance of activists.",
	},
	greece: {
		name: "Greece",
		continent: "europe",
		status: "green",
		legal: "Legalized same-sex marriage in 2024.",
		health: "Strong support in Athens and Mykonos.",
	},
	grenada: {
		name: "Grenada",
		continent: "americas",
		status: "yellow",
		legal: "Legal; social stigma is decreasing.",
		health: "Basic care available.",
	},
	guatemala: {
		name: "Guatemala",
		continent: "americas",
		status: "yellow",
		legal: "Legal, but high religious opposition.",
		health: "Limited specialized care.",
	},
	guinea: {
		name: "Guinea",
		continent: "africa",
		status: "red",
		legal: "Illegal; high risk.",
		health: "No resources.",
	},
	"guinea-bissau": {
		name: "Guinea-Bissau",
		continent: "africa",
		status: "red",
		legal: "Legal, but no protection laws.",
		health: "No resources.",
	},
	guyana: {
		name: "Guyana",
		continent: "americas",
		status: "red",
		legal: "Decriminalized cross-dressing, but same-sex acts still illegal.",
		health: "Limited support.",
	},
	haiti: {
		name: "Haiti",
		continent: "americas",
		status: "yellow",
		legal: "Legal, but extremely high societal violence.",
		health: "Dangerous to access care.",
	},
	honduras: {
		name: "Honduras",
		continent: "americas",
		status: "yellow",
		legal: "Legal, but high rates of targeted violence.",
		health: "NGO support in San Pedro Sula.",
	},
	hungary: {
		name: "Hungary",
		continent: "europe",
		status: "yellow",
		legal: "Civil unions legal, but 'propaganda' bans active.",
		health: "Stigma in state clinics.",
	},
	iceland: {
		name: "Iceland",
		continent: "europe",
		status: "green",
		legal: "Ranked #1 safest country; full equality.",
		health: "Global gold standard.",
	},
	india: {
		name: "India",
		continent: "asia",
		status: "yellow",
		legal: "Decriminalized in 2018; marriage not yet legal.",
		health: "Huge community networks in Mumbai and Delhi.",
	},
	indonesia: {
		name: "Indonesia",
		continent: "asia",
		status: "red",
		legal: "Legal (except Aceh), but high persecution and raids.",
		health: "High discrimination risk.",
	},
	iran: {
		name: "Iran",
		continent: "asia",
		status: "red",
		legal: "Illegal; carries the death penalty.",
		health: "State-forced gender surgery only.",
	},
	iraq: {
		name: "Iraq",
		continent: "asia",
		status: "red",
		legal: "Formally criminalized 'sodomy' and 'gender transition' in 2024.",
		health: "Gender-affirming care is explicitly illegal; high physical risk.",
		posture: "Extremely Hostile.",
	},
	ireland: {
		name: "Ireland",
		continent: "europe",
		status: "green",
		legal: "Marriage equality via public vote; very safe.",
		health: "Excellent inclusive care.",
	},
	israel: {
		name: "Israel",
		continent: "asia",
		status: "green",
		legal: "Middle East leader in rights; safe for travel.",
		health: "Specialized clinics in Tel Aviv.",
	},
	italy: {
		name: "Italy",
		continent: "europe",
		status: "green",
		legal: "Civil unions legal; safe for travel.",
		health: "Reliable care in major cities.",
	},
	"ivory-coast": {
		name: "Ivory Coast",
		continent: "africa",
		status: "yellow",
		legal: "Legal, but no protection laws.",
		health: "NGO support in Abidjan.",
	},
	jamaica: {
		name: "Jamaica",
		continent: "americas",
		status: "red",
		legal: "Illegal; high social risk outside of resorts.",
		health: "High stigma in public health.",
	},
	japan: {
		name: "Japan",
		continent: "asia",
		status: "yellow",
		legal:
			"Most major cities now issue partnership certificates. High court case pending 2026.",
		health:
			"Safe, but bureaucratic; medical gender transition still requires diagnosis.",
		posture: "Socially tolerant; legal system is in active transition.",
	},
	jordan: {
		name: "Jordan",
		continent: "asia",
		status: "red",
		legal: "Legal, but 'morality' laws applied; high stigma.",
		health: "No specialized services.",
	},
	kazakhstan: {
		name: "Kazakhstan",
		continent: "asia",
		status: "red",
		legal:
			"Signed Jan 2026: New laws ban 'LGBTQ propaganda' with prison threats.",
		health: "Visibility in healthcare settings is now a legal risk.",
		posture: "Hostile - Following the 'Russia-style' censorship model.",
	},
	kenya: {
		name: "Kenya",
		continent: "africa",
		status: "orange",
		legal:
			"Same-sex acts remain illegal (14-21 years). 'Family Protection Bill' currently in parliament (Feb 2026) seeks to mimic Uganda's harsher laws.",
		health:
			"Safe Access: Pema Kenya (Mombasa) and NGLHRC (Nairobi) provide legal aid and health referrals. Use 'Jali Yetu' (Our Care) project clinics for identity-affirming care.",
		posture:
			"Elevated - Watch for Supreme Court rulings on the 'Family Protection Bill' expected by mid-2026.",
	},
	kiribati: {
		name: "Kiribati",
		continent: "oceania",
		status: "yellow",
		legal: "Illegal for men; social stigma is high.",
		health: "Basic care only.",
	},
	kuwait: {
		name: "Kuwait",
		continent: "asia",
		status: "red",
		legal: "Strictly illegal; harassment common.",
		health: "No resources.",
	},
	kyrgyzstan: {
		name: "Kyrgyzstan",
		continent: "asia",
		status: "red",
		legal: "Legal, but 'propaganda' laws similar to Russia.",
		health: "High medical stigma.",
	},
	laos: {
		name: "Laos",
		continent: "asia",
		status: "red",
		legal: "No laws against it; social 'invisibility' is high.",
		health: "Limited care.",
	},
	latvia: {
		name: "Latvia",
		continent: "europe",
		status: "green",
		legal: "Civil unions legal since 2024.",
		health: "Inclusive in Riga.",
	},
	lebanon: {
		name: "Lebanon",
		continent: "asia",
		status: "red",
		legal: "Unclear laws; raids on queer spaces common.",
		health: "Good NGOs but high risk.",
	},
	lesotho: {
		name: "Lesotho",
		continent: "africa",
		status: "yellow",
		legal: "Decriminalized in 2012.",
		health: "Minimal support.",
	},
	liberia: {
		name: "Liberia",
		continent: "africa",
		status: "red",
		legal: "Strictly illegal.",
		health: "No resources.",
	},
	libya: {
		name: "Libya",
		continent: "africa",
		status: "red",
		legal: "Illegal; extremely unsafe.",
		health: "No resources.",
	},
	liechtenstein: {
		name: "Liechtenstein",
		continent: "europe",
		status: "green",
		legal: "Marriage equality officially in effect since 2025.",
		health:
			"Inclusive and integrated into the broader European health network.",
		posture: "Stable and protective.",
	},
	lithuania: {
		name: "Lithuania",
		continent: "europe",
		status: "green",
		legal: "Legal, but 'protection of minors' laws limit visibility.",
		health: "Generally safe.",
	},
	luxembourg: {
		name: "Luxembourg",
		continent: "europe",
		status: "green",
		legal: "Full marriage equality; very safe.",
		health: "Top-tier inclusive care.",
	},
	madagascar: {
		name: "Madagascar",
		continent: "africa",
		status: "yellow",
		legal: "Legal, but high poverty limits support.",
		health: "Basic care.",
	},
	malawi: {
		name: "Malawi",
		continent: "africa",
		status: "yellow",
		legal: "Laws suspended, but social stigma remains.",
		health: "Developing NGO care.",
	},
	malaysia: {
		name: "Malaysia",
		continent: "asia",
		status: "red",
		legal: "Illegal; state-led persecution.",
		health: "Very high medical stigma.",
	},
	maldives: {
		name: "Maldives",
		continent: "asia",
		status: "red",
		legal: "Illegal; safe only in private tourist resorts.",
		health: "No community resources.",
	},
	mali: {
		name: "Mali",
		continent: "africa",
		status: "red",
		legal: "Legal, but extremely high religious and safety risks.",
		health: "Non-existent.",
	},
	malta: {
		name: "Malta",
		continent: "europe",
		status: "green",
		legal: "Often ranked #1 in Europe for LGBTQ+ rights.",
		health: "Excellent specialized clinics.",
	},
	"marshall-islands": {
		name: "Marshall Islands",
		continent: "oceania",
		status: "green",
		legal: "Decriminalized in 2011; safe.",
		health: "Small community support.",
	},
	mauritania: {
		name: "Mauritania",
		continent: "africa",
		status: "red",
		legal: "Death penalty exists (though rarely applied).",
		health: "No resources.",
	},
	mauritius: {
		name: "Mauritius",
		continent: "africa",
		status: "green",
		legal: "Decriminalized in 2023.",
		health: "Inclusive private clinics.",
	},
	mexico: {
		name: "Mexico",
		continent: "americas",
		status: "green",
		legal: "Marriage equality nationwide; very gay-friendly cities.",
		health: "Excellent care in Mexico City and Vallarta.",
	},
	micronesia: {
		name: "Micronesia",
		continent: "oceania",
		status: "green",
		legal: "Never criminalized; safe.",
		health: "Basic support.",
	},
	moldova: {
		name: "Moldova",
		continent: "europe",
		status: "green",
		legal: "Legalized, with improving anti-bias laws.",
		health: "Support in Chisinau.",
	},
	monaco: {
		name: "Monaco",
		continent: "europe",
		status: "green",
		legal: "Civil unions; very safe.",
		health: "High standard of care.",
	},
	mongolia: {
		name: "Mongolia",
		continent: "asia",
		status: "yellow",
		legal: "Anti-discrimination laws exist.",
		health: "LGBT Centre in Ulaanbaatar.",
	},
	montenegro: {
		name: "Montenegro",
		continent: "europe",
		status: "green",
		legal: "Same-sex partnerships are legal.",
		health: "Inclusive in coastal cities.",
	},
	morocco: {
		name: "Morocco",
		continent: "africa",
		status: "red",
		legal: "Illegal; frequent arrests and social harassment.",
		health: "High medical stigma.",
	},
	mozambique: {
		name: "Mozambique",
		continent: "africa",
		status: "yellow",
		legal: "Decriminalized in 2015.",
		health: "Developing support.",
	},
	myanmar: {
		name: "Myanmar",
		continent: "asia",
		status: "red",
		legal: "Strictly illegal; unsafe due to political unrest.",
		health: "Non-existent.",
	},
	namibia: {
		name: "Namibia",
		continent: "africa",
		status: "yellow",
		legal: "Decriminalized in 2024 by high court.",
		health: "Active support in Windhoek.",
	},
	nauru: {
		name: "Nauru",
		continent: "oceania",
		status: "yellow",
		legal: "Decriminalized in 2016.",
		health: "Limited resources.",
	},
	nepal: {
		name: "Nepal",
		continent: "asia",
		status: "yellow",
		legal: "Marriage equality recognized by courts.",
		health: "Blue Diamond Society support.",
	},
	netherlands: {
		name: "Netherlands",
		continent: "europe",
		status: "green",
		legal: "First in the world to legalize gay marriage (2001).",
		health: "Extensive, world-class care.",
	},
	"new-zealand": {
		name: "New Zealand",
		continent: "oceania",
		status: "green",
		legal: "Extremely progressive; full equality.",
		health: "Specialized national care.",
	},
	nicaragua: {
		name: "Nicaragua",
		continent: "americas",
		status: "red",
		legal: "Legal, but high state-led political risk.",
		health: "Limited resources.",
	},
	niger: {
		name: "Niger",
		continent: "africa",
		status: "red",
		legal: "Legal, but culturally strictly forbidden.",
		health: "No resources.",
	},
	nigeria: {
		name: "Nigeria",
		continent: "africa",
		status: "red",
		legal:
			"SSMPA (2013) remains in force. 14 years prison for 'homosexual acts'. Sharia law in North carries death penalty.",
		health:
			"Private Care Only: Use 'TIERS' (The Initiative for Equal Rights) or 'Improved Sexual Health and Rights Advocacy Initiative'. Never disclose status in federal hospitals.",
		posture:
			"High Alert - Increase in 'Kito' blackmail gangs reported in Lagos and Abuja this month (Feb 2026).",
	},
	niue: {
		name: "Niue",
		continent: "oceania",
		status: "green",
		legal: "Legal; welcoming.",
		health: "Basic care.",
	},
	"north-korea": {
		name: "North Korea",
		continent: "asia",
		status: "red",
		legal: "No specific laws, but total social control.",
		health: "Non-existent care.",
	},
	"north-macedonia": {
		name: "North Macedonia",
		continent: "europe",
		status: "green",
		legal: "Legalized with developing protections.",
		health: "Support in Skopje.",
	},
	norway: {
		name: "Norway",
		continent: "europe",
		status: "green",
		legal: "Consistently ranked among the safest globally.",
		health: "Universal inclusive care.",
	},
	oman: {
		name: "Oman",
		continent: "asia",
		status: "red",
		legal: "Strictly illegal.",
		health: "No resources.",
	},
	pakistan: {
		name: "Pakistan",
		continent: "asia",
		status: "red",
		legal: "Strictly illegal; trans rights exist but are under threat.",
		health: "NGO-led care only.",
	},
	palau: {
		name: "Palau",
		continent: "oceania",
		status: "green",
		legal: "Decriminalized in 2014.",
		health: "Welcoming.",
	},
	palestine: {
		name: "Palestine",
		continent: "asia",
		status: "red",
		legal: "Illegal in Gaza; high social risk in West Bank.",
		health: "Non-existent care.",
	},
	panama: {
		name: "Panama",
		continent: "americas",
		status: "yellow",
		legal: "Legal, but constitutional marriage ban.",
		health: "Reliable private care.",
	},
	"papua-new-guinea": {
		name: "Papua New Guinea",
		continent: "oceania",
		status: "red",
		legal: "Illegal; high social violence.",
		health: "No safe care.",
	},
	paraguay: {
		name: "Paraguay",
		continent: "americas",
		status: "red",
		legal: "Legal, but very high levels of intolerance.",
		health: "Poor inclusive care.",
	},
	peru: {
		name: "Peru",
		continent: "americas",
		status: "yellow",
		legal: "Legal, but no protection laws.",
		health: "Support in Lima.",
	},
	philippines: {
		name: "Philippines",
		continent: "asia",
		status: "yellow",
		legal:
			"As of Jan 10, 2026, Supreme Court recognizes cohabitation/property rights, but marriage remains blocked.",
		health:
			"Local ordinances (like Quezon City) ban conversion therapy as of 2025.",
		posture: "Improving - Strong local protections despite national stalemate.",
	},
	poland: {
		name: "Poland",
		continent: "europe",
		status: "green",
		legal: "Legal, but 'LGBT-free zones' (now mostly abolished).",
		health: "Safe in major cities.",
	},
	portugal: {
		name: "Portugal",
		continent: "europe",
		status: "green",
		legal: "Top-tier legal rights and marriage equality.",
		health: "Highly specialized clinics.",
	},
	qatar: {
		name: "Qatar",
		continent: "asia",
		status: "red",
		legal: "Strictly illegal; high risk.",
		health: "No resources.",
	},
	romania: {
		name: "Romania",
		continent: "europe",
		status: "green",
		legal: "Legal, but high social opposition.",
		health: "Support in Bucharest.",
	},
	russia: {
		name: "Russia",
		continent: "europe",
		status: "red",
		legal: "Extreme 'propaganda' bans; 'extremist' designation.",
		health: "Dangerous to access.",
	},
	rwanda: {
		name: "Rwanda",
		continent: "africa",
		status: "yellow",
		legal:
			"Not criminalized, but marriage is constitutionally banned. Often used 'vagrancy' or 'deviant behavior' laws to detain individuals.",
		health:
			"Moderate Access: Kigali has discrete clinics. Trans health is severely limited; 'ibishegabo' (trans men) often face spectacle/shaming in hospitals. Use private Kigali referrals.",
		posture:
			"Cautious - Government maintains a 'private matter' stance to keep donors happy, but social stigma is extreme.",
	},
	samoa: {
		name: "Samoa",
		continent: "oceania",
		status: "yellow",
		legal: "Illegal for men; Fa'afafine culturally accepted.",
		health: "Mixed care.",
	},
	"san-marino": {
		name: "San Marino",
		continent: "europe",
		status: "green",
		legal: "Civil unions legal; very safe.",
		health: "Excellent care.",
	},
	"sao-tome-and-principe": {
		name: "Sao Tome and Principe",
		continent: "africa",
		status: "yellow",
		legal: "Decriminalized in 2012.",
		health: "Limited resources.",
	},
	"saudi-arabia": {
		name: "Saudi Arabia",
		continent: "asia",
		status: "red",
		legal: "Illegal; carries death penalty.",
		health: "No resources.",
	},
	senegal: {
		name: "Senegal",
		continent: "africa",
		status: "red",
		legal: "Strictly illegal; high harassment.",
		health: "No safe care.",
	},
	serbia: {
		name: "Serbia",
		continent: "europe",
		status: "yellow",
		legal: "Legal, but Pride remains controversial.",
		health: "Strong trans care in Belgrade.",
	},
	seychelles: {
		name: "Seychelles",
		continent: "africa",
		status: "green",
		legal: "Decriminalized in 2016.",
		health: "Welcoming.",
	},
	"sierra-leone": {
		name: "Sierra Leone",
		continent: "africa",
		status: "red",
		legal: "Illegal for men.",
		health: "No resources.",
	},
	singapore: {
		name: "Singapore",
		continent: "asia",
		status: "green",
		legal: "Decriminalized in 2022.",
		health: "Top-tier inclusive care.",
	},
	slovakia: {
		name: "Slovakia",
		continent: "europe",
		status: "green",
		legal: "Legal, but recent increases in bias.",
		health: "Reliable in Bratislava.",
	},
	slovenia: {
		name: "Slovenia",
		continent: "europe",
		status: "green",
		legal: "Marriage equality and adoption rights.",
		health: "Highly inclusive.",
	},
	"solomon-islands": {
		name: "Solomon Islands",
		continent: "oceania",
		status: "yellow",
		legal: "Illegal for men.",
		health: "Limited care.",
	},
	somalia: {
		name: "Somalia",
		continent: "africa",
		status: "red",
		legal: "Illegal; death penalty in some areas.",
		health: "No resources.",
	},
	"south-africa": {
		name: "South Africa",
		continent: "africa",
		status: "green",
		legal: "Constitutionally protected. Same-sex marriage is legal.",
		health:
			"Best Access: 'OUT LGBT Well-being' (Pretoria) and 'Triangle Project' (Cape Town). Warning: 2026 UCT study shows 15-year waitlists for surgery in public sector; use NGO clinics for HRT/HIV care.",
		posture:
			"Stable - Safe haven for regional refugees, though 'Corrective Violence' remains a high risk in townships.",
	},
	"south-korea": {
		name: "South Korea",
		continent: "asia",
		status: "green",
		legal: "Legal, but high social pressure and no anti-bias laws.",
		health: "Excellent specialized clinics.",
	},
	"south-sudan": {
		name: "South Sudan",
		continent: "africa",
		status: "red",
		legal: "Strictly illegal.",
		health: "No resources.",
	},
	spain: {
		name: "Spain",
		continent: "europe",
		status: "green",
		legal: "Global leader in LGBTQ+ freedom.",
		health: "Universal, world-class inclusive care.",
	},
	"sri-lanka": {
		name: "Sri Lanka",
		continent: "asia",
		status: "red",
		legal: "Decriminalization pending court ruling; high stigma.",
		health: "Support in Colombo.",
	},
	sudan: {
		name: "Sudan",
		continent: "africa",
		status: "red",
		legal: "Illegal; severe penalties.",
		health: "No resources.",
	},
	suriname: {
		name: "Suriname",
		continent: "americas",
		status: "yellow",
		legal: "Decriminalized; society is generally tolerant.",
		health: "Limited care.",
	},
	sweden: {
		name: "Sweden",
		continent: "europe",
		status: "green",
		legal: "Top-tier rights and safety.",
		health: "Highly specialized national care.",
	},
	switzerland: {
		name: "Switzerland",
		continent: "europe",
		status: "green",
		legal: "Marriage equality legalized in 2022.",
		health: "Excellent healthcare.",
	},
	syria: {
		name: "Syria",
		continent: "asia",
		status: "red",
		legal: "Illegal; extremely unsafe.",
		health: "No resources.",
	},
	taiwan: {
		name: "Taiwan",
		continent: "asia",
		status: "green",
		legal: "First in Asia to legalize gay marriage.",
		health: "Inclusive and specialized centers.",
	},
	tajikistan: {
		name: "Tajikistan",
		continent: "asia",
		status: "red",
		legal: "Legal, but state maintains 'registry' of queer people.",
		health: "Very high risk.",
	},
	tanzania: {
		name: "Tanzania",
		continent: "africa",
		status: "red",
		legal:
			"Consensual same-sex acts carry 30 years to life imprisonment. Zanzibar has separate, strict laws (5 years for women).",
		health:
			"HIGH RISK: Government crackdown on HIV outreach for MSM (Men who Sex with Men) is active. Use 'Community Health Services' through discrete NGOs only. Do not use state-run HIV portals.",
		posture:
			"High Alert - 2026 reports of forced anal examinations and arbitrary arrests in Dar es Salaam.",
	},
	thailand: {
		name: "Thailand",
		continent: "asia",
		status: "green",
		legal:
			"Marriage Equality Law officially took effect Jan 23, 2025. Full adoption rights granted.",
		health:
			"Global hub for gender-affirming care; highly inclusive public/private systems.",
		posture: "Highly Safe - 2026 regional leader.",
	},
	"timor-leste": {
		name: "Timor-Leste",
		continent: "asia",
		status: "yellow",
		legal: "Legal; generally safe.",
		health: "Limited resources.",
	},
	togo: {
		name: "Togo",
		continent: "africa",
		status: "red",
		legal: "Strictly illegal.",
		health: "No resources.",
	},
	tonga: {
		name: "Tonga",
		continent: "oceania",
		status: "yellow",
		legal: "Illegal for men; Leiti community cultural role.",
		health: "Limited care.",
	},
	"trinidad-and-tobago": {
		name: "Trinidad and Tobago",
		continent: "americas",
		status: "red",
		legal:
			"URGENT: Recriminalized in March 2025. The Court of Appeal overturned the 2018 decriminalization ruling.",
		health:
			"Public stigma increasing; legal protections for patients have weakened.",
		posture: "Hostile - High monitoring of 2026 court challenges advised.",
	},
	tunisia: {
		name: "Tunisia",
		continent: "africa",
		status: "red",
		legal: "Illegal; frequent arrests and anal testing.",
		health: "High medical stigma.",
	},
	turkey: {
		name: "Turkey",
		continent: "asia",
		status: "yellow",
		legal: "Legal, but high state-led hostility.",
		health: "Support groups in Istanbul.",
	},
	turkmenistan: {
		name: "Turkmenistan",
		continent: "asia",
		status: "red",
		legal: "Illegal; high risk.",
		health: "No resources.",
	},
	tuvalu: {
		name: "Tuvalu",
		continent: "oceania",
		status: "yellow",
		legal: "Illegal for men.",
		health: "Basic care.",
	},
	uganda: {
		name: "Uganda",
		continent: "africa",
		status: "red",
		legal:
			"Death penalty possible for 'aggravated homosexuality'. 2026 Election cycle has increased police targeting of suspected safe-houses.",
		health:
			"HIGH RISK: Recent US-Uganda health agreements (Feb 2026) have shifted funding to govt clinics. Avoid state facilities. Contact 'Sexual Minorities Uganda (SMUG)' for a list of vetted, underground providers.",
		posture:
			"Critical - Active 'Kito' (trap) attacks on dating apps and house raids reported Feb 2026.",
	},
	ukraine: {
		name: "Ukraine",
		continent: "europe",
		status: "yellow",
		legal: "Legal; partnerships pending in parliament.",
		health: "NGO support active despite war.",
	},
	"united-arab-emirates": {
		name: "United Arab Emirates",
		continent: "asia",
		status: "red",
		legal: "Strictly illegal; risk for trans travelers.",
		health: "No community resources.",
	},
	"united-kingdom": {
		name: "United Kingdom",
		continent: "europe",
		status: "green",
		legal: "Full marriage equality and protections.",
		health: "NHS specialized LGBTQ+ clinics.",
	},
	"united-states": {
		name: "United States",
		continent: "americas",
		status: "green",
		legal: "Marriage equality; rights vary significantly by state.",
		health: "Excellent specialized networks.",
		posture: "2026 Monitoring: High-profile federal trials ongoing.",
	},
	uruguay: {
		name: "Uruguay",
		continent: "americas",
		status: "green",
		legal: "Most progressive country in South America.",
		health: "Highly inclusive healthcare.",
	},
	uzbekistan: {
		name: "Uzbekistan",
		continent: "asia",
		status: "red",
		legal: "Illegal for men.",
		health: "No resources.",
	},
	vanuatu: {
		name: "Vanuatu",
		continent: "oceania",
		status: "yellow",
		legal: "Legal; safe for travel.",
		health: "Basic care.",
	},
	"vatican-city": {
		name: "Vatican City",
		continent: "europe",
		status: "yellow",
		legal: "No specific laws; based on Italian law.",
		health: "N/A.",
	},
	venezuela: {
		name: "Venezuela",
		continent: "americas",
		status: "yellow",
		legal: "Legal, but high state collapse and bias.",
		health: "Poor healthcare access.",
	},
	vietnam: {
		name: "Vietnam",
		continent: "asia",
		status: "yellow",
		legal: "Very tolerant; no laws against pride.",
		health: "Improving specialized care.",
	},
	yemen: {
		name: "Yemen",
		continent: "asia",
		status: "red",
		legal: "Illegal; death penalty.",
		health: "No resources.",
	},
	zambia: {
		name: "Zambia",
		continent: "africa",
		status: "red",
		legal: "Strictly illegal.",
		health: "No resources.",
	},
	zimbabwe: {
		name: "Zimbabwe",
		continent: "africa",
		status: "red",
		legal: "Illegal; high social risk.",
		health: "Minimal support.",
	},
	"antigua-and-barbuda": {
		name: "Antigua and Barbuda",
		continent: "americas",
		status: "green",
		legal: "Decriminalized in 2022.",
		health: "Basic inclusive care.",
	},
	comoros: {
		name: "Comoros",
		continent: "africa",
		status: "red",
		legal: "Illegal; strictly conservative.",
		health: "No resources.",
	},
	"equatorial-guinea": {
		name: "Equatorial Guinea",
		continent: "africa",
		status: "red",
		legal: "Legal, but extreme social repression.",
		health: "No resources.",
	},
	grenada: {
		name: "Grenada",
		continent: "americas",
		status: "green",
		legal: "Decriminalized in 2024.",
		health: "Developing support.",
	},
	kosovo: {
		name: "Kosovo",
		continent: "europe",
		status: "yellow",
		legal:
			"Legal; constitution prohibits discrimination, but social stigma is high.",
		health: "Support available in Pristina.",
		posture: "Stable - Monitoring EU integration requirements.",
	},
	mauritius: {
		name: "Mauritius",
		continent: "africa",
		status: "green",
		legal: "Decriminalized in 2023.",
		health: "Inclusive clinics.",
	},
	"saint-kitts-and-nevis": {
		name: "Saint Kitts and Nevis",
		continent: "americas",
		status: "green",
		legal: "Decriminalized in 2022.",
		health: "Welcoming for tourists.",
	},
	"saint-lucia": {
		name: "Saint Lucia",
		continent: "red",
		legal: "Illegal for men; laws rarely enforced.",
		health: "Limited resources.",
	},
	somaliland: {
		name: "Somaliland",
		continent: "africa",
		status: "red",
		legal:
			"Unrecognized state. Sharia law applies. 2025-2026 seen a 'significant number' of gay men sentenced to 8+ years.",
		health:
			"No Safe Access: Extreme risk. Health services are non-existent for LGBTQ+ individuals. Evacuation/Migration is the only current safety recommendation.",
		posture:
			"Hostile - Complete invisibility required for survival. Active military court trials.",
	},
	"south-ossetia": {
		name: "South Ossetia",
		continent: "europe",
		status: "red",
		legal: "Unregulated; effectively mirrors Russian 'propaganda' bans.",
		health: "Non-existent.",
	},
	transnistria: {
		name: "Transnistria",
		continent: "europe",
		status: "red",
		legal: "Legal, but high state surveillance and Russian influence.",
		health: "No safe resources.",
	},
	"western-sahara": {
		name: "Western Sahara",
		continent: "africa",
		status: "red",
		legal: "Illegal (Moroccan Penal Code applies in controlled areas).",
		health: "No resources.",
	},
};
